### ISSUE TITLE
Seems not complete

### ISSUE THREAD

**Issue by qiaolinhan** [logicguy1/PH-DL#2]
When I tried to run it with __python main.py__. It shows __ [!] Falied loading modules, make sure you cloned all the files from the github, press enter to exit__
![Screenshot 2024-07-19 132041](https://github.com/user-attachments/assets/b272ec73-8eae-47f9-8a9b-f2b1291d5645)

**Comment by rockydonet** [comment]
First, make sure python is installed.
If not, go to https://www.python.org/downloads/
Run the installer.
On the “Advanced Options” screen, tick ✅ “Add Python to environment variables”
Click Install

After it done, follow below steps:
Open Command Prompt or PowerShell, and run:
python -m pip install youtube_dl

Quick Explanation:
youtube_dl is a Python package for downloading videos from YouTube and other sites.
It’s not included with Python by default — so your script needs you to install it manually.

**Comment by burner3x6** [comment]
im running into this warning when i run main.py:

WARNING: 66e9265ba98fd: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.
Traceback (most recent call last):
  File "c:\Users\ClntK\Downloads\PH-DL\main.py", line 115, in <module>
    modules[option]["function"]()
  File "c:\Users\ClntK\Downloads\PH-DL\modules\videoDownloader.py", line 41, in main
    ).send()
AttributeError: 'Notification' object has no attribute 'send'


i installed ffmpeg with pip... the error persists. 

can you help?

**Comment by burner3x6** [comment]
im running into this warning when i run main.py:

WARNING: 66e9265ba98fd: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.
Traceback (most recent call last):
File "c:\Users\<username>\Downloads\PH-DL\main.py", line 115, in
modules[option]["function"](https://github.com/logicguy1/PH-DL/issues/2)
File "c:\Users\<username>\Downloads\PH-DL\modules\videoDownloader.py", line 41, in main
).send()
AttributeError: 'Notification' object has no attribute 'send'

i installed ffmpeg with pip... the error persists.

avconv returns:

**ERROR: Could not find a version that satisfies the requirement avconv (from versions: none)
ERROR: No matching distribution found for avconv**

can you help?

**Comment by rockydonet** [comment]
Hello, try below steps to install ffmpeg in correct way.

1. Download ffmpeg Windows builds from gyan.dev. Link is https://www.gyan.dev/ffmpeg/builds/
2. Download ffmpeg-git-full.7z from above link. Unzip and rename folder to ffmpeg.
3. Copy folder ffmpeg into C drive. Result will be C:/ffmpeg/
4. Edit PATH in Windows system Environment Variables, add C:\ffmpeg\bin in PATH.
5. Now CLOSE CMD if you already start it. Re-open CMD and go to PH-DL folder.
6. TYPE:  python main.py.

By doing above steps, warning message "66e9265ba98fd: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically." will be fixed.

Have a try.

**Comment by Salarsdg** [comment]
hello , i have these error on linux server , how should i fixed that ? 

Traceback (most recent call last):
  File "/root/PH-DL/main.py", line 115, in <module>
    modules[option]["function"]()
  File "/root/PH-DL/modules/videoDownloader.py", line 41, in main
    ).send()
      ^^^^
AttributeError: 'Notification' object has no attribute 'send'

**Comment by logicguy1** [comment]
There was just made a pr that i think would fix these issues
